version: "3.2"
services:
  php:
    build: './php/'
    volumes:
      - ./public_html/:/var/www/html/
  apache:
    build: './apache/'
    depends_on:
      - php
      - mysql
    ports:
      - "8080:80"
    volumes:
      - ./php/composer.json:/var/www/html/composer.json
      - ./public_html/:/var/www/html/
  mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
volumes:
  db_data: